### ISSUE TITLE
Backup vines from other users

### ISSUE THREAD

**Issue by emersion** [phiphou/vine-backup#1]
Is it possible to add another parameter to export vines of another user?

**Comment by phiphou** [comment]
No, not now, but I plan to add parameter to export not only user's Vines but also the ones he liked. (probably in a few hours, so stay tunned ;) )

I'm going to think about your idea (adding "another user") , but I assume you want to work with user names and not ids, don't you ? I also assume you want to be able to work with a list of users, and not only a single user, dont'you ?

**Comment by phiphou** [comment]
Latest release ([v1.2.0](https://github.com/phiphou/vine-backup/releases/tag/v1.2.0)) adds this feature.

As Vine API doesn't offer a multi users search, I decided to not handle users list at this time.

You can find [instructions](https://github.com/phiphou/vine-backup#any-user-vines) in the updated [README.md](https://github.com/phiphou/vine-backup#readme)

@emersion : Hope it fill your needs ;) !
