### ISSUE TITLE
Omit Revines/Reposts

### ISSUE THREAD

**Issue by aren55555** [phiphou/vine-backup#2]
Hey, was just wondering if it would be possible to add an option to omit the revines/reposts; such that I only get my original content.

**Comment by phiphou** [comment]
Very good idea ;) 

I added this feature in the [v1.4.0](https://github.com/phiphou/vine-backup/releases/tag/v1.4.0).

See [instructions ](https://github.com/phiphou/vine-backup#no_reposts) in [`readme.md`](https://github.com/phiphou/vine-backup#readme).

Hope it will fit your needs ;)

**Comment by phiphou** [comment]
I reopened the issue, waiting for you to let me know if it works for you like you wanted ;)

**Comment by aren55555** [comment]
See https://github.com/phiphou/vine-backup/pull/3
