### ISSUE TITLE
Incorrect number / timeout

### ISSUE THREAD

**Issue by dotgodly** [phiphou/vine-backup#5]
With just email and password set, the app only retrieves 181 vines. With --likes set, it times out. I have 995 posts and 11,940 likes.

**Comment by phiphou** [comment]
Unable to reproduce without your Vine user name. Maybe you should try the --list option.

**Comment by dotgodly** [comment]
--list still gives me 181 vines. My user ID is 996123084295905280.

**Comment by phiphou** [comment]
Vine api is not responding anymore, so I"m closing this.
